baseURL: "https://Nico1eLi.github.io"
languageCode: "zh-cn"
title: "Guo LI"

module:
  imports:
    - path: github.com/gurusabarish/hugo-profile


params:
  title: "Guo LI"
  description: "Welcome to my personal website !"
  
  # 个人资料设置
  hero:
    enable: true
    intro: "Hi, I'm"
    title: "Guo LI"
    subtitle: "PhD Student"
    content: "在这里分享我的学习和生活"
    image: /images/hero.jpg  # 待会我们添加图片
    button:
      enable: true
      name: "More"
      url: "#about"
      download: false

  # About部分设置
  about:
    enable: true
    title: "About Me"
    image: "/images/avatar.jpg"  # 待会我们添加图片
    content: |-
      Hi, there~
      Currently, I am a Ph.D. student in the *Department of Government and Public Administration*, *Faculty of Social Sciences* at the *University of Macau*. My research interests lie in the field of comparative politics, with a particular focus on cultural governance, entertainment politics, and celebrity politics under authoritarian regimes.** 
      If you have any questions about my research or would like to discuss potential collaboration opportunities, please feel free to reach out to me.

    skills:
      enable: true
      title: "Skills"
      items:
        - "Quantitative Method"
        - "SPSS, Stata, R, Python"
        - "Text analysis"

  # 社交媒体链接
  socialLinks:
    - name: github
      url: https://github.com/Nico1eLi