baseURL: "https://Nico1eLi.github.io/"
languageCode: "en-us"
title: "Guo LI"
theme: "hugo-profile"

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  title: "Guo LI"
  description: "PhD Student"
  customCSS: true
  # [新增] 暗黑模式
  darkMode: false

  hero:
    enable: true
    intro: "Hi, I'm"
    title: "Guo LI"
    subtitle: "Thinking & Exploring"
    content: "PhD Student"
    image: "/images/hero.jpg"
    button:
      enable: true
      name: "More"
      url: "#about"
    socialLinks:
      fontAwesomeIcons:
        - icon: fas fa-envelope
          url: "mailto:nico1elee@outlook.com"
        - icon: fab fa-github
          url: "https://github.com/Nico1eLi"    

  about:
    enable: true
    title: "About Me"
    image: "/images/about.jpg"
    content: |-
      Hi, there~

      Currently, I am a Ph.D. student in the Department of Government and Public Administration, Faculty of Social Sciences at the University of Macau. My research interests lie in the field of comparative politics, with a particular focus on cultural governance, entertainment politics, and celebrity politics under authoritarian regimes.

      If you have any questions about my research or would like to discuss potential collaboration opportunities, please feel free to reach out to me.

  experience:
    enable: true
    title: "Research"
    items:
      - job: "Selected Publications"
        company: "Publications"
        info:
          enable: false
        content: |-
          - "Authoritarian Stardom: Coopting Entertainment Celebrities to Serve the State" with *Chengli Wang*, under review
          - “The Star Effect: How Celebrity Propaganda Shapes Public Opinion in China” with *Chengli Wang*, Work in Progress
          - “ Patriotism or Exclusion? Gender Inequality in Authoritarian Cultural Production”, Work in Progress
          - "Celebrity Politics and NGOs advocacy in Digital Age" (PhD dissertation, work in progress)
          - "Cultural Governance and Entertainment Politics" (Work in Progress)

      - job: "Academic Events"
        company: "Academic Events"
        info:
          enable: false
        content: |-
          -   Sept. 2025 **2025 121st APSA Annual Meeting**, Vancouver, BC, Canada
          -   Sept. 2024 **2024 120th APSA Annual Meeting**, Philadelphia, PA, USA
          -   Jul. 2024 **17th Annual Meeting of Chinese Community of Political Science and International Studies**, Tsinghua University, Beijing, China
          -   Mar. 2024 **2nd DGPA Student Research Symposium**, DGPA, University of Macau, Macau SAR
          -   Mar. 2023 **PhD and MSS student research symposium** , DGPA, University of Macau, Macau SAR
          

  achievements:
    enable: true
    title: "Education"
    items:
      - title: Ph.D. in Government and Public Administration
        content: University of Macau, 2023-Present
        url: "https://www.um.edu.mo/"
        
      - title: MSS in International Relations and Public Policy
        content: University of Macau, 2021-2023
        url: "https://www.um.edu.mo/"
        
      - title: LL.B in Politics, Philosophy and Economics
        content: Renmin University of China, 2017-2021
        url: "https://www.ruc.edu.cn/"

  cv:
    enable: true
    title: "Curriculum Vitae"
    content: |-
              You can download my CV [here](https://www.dropbox.com/scl/fi/mkay1zergk4bo7jz81lqc/cv.pdf?rlkey=t8p9j853t4u4het69utiw0pfq&st=ef8kjhqc&dl=0).

