name: Deploy Hugo site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Hugo
        run: |
          wget -O ${{ runner.temp }}/hugo_extended.deb https://github.com/gohugoio/hugo/releases/download/v0.120.4/hugo_extended_0.120.4_linux-amd64.deb
          sudo dpkg -i ${{ runner.temp }}/hugo_extended.deb

      - name: Build with Hugo
        run: hugo --minify

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Create and switch to gh-pages branch
          git checkout -b gh-pages
          
          # Remove all files except public content
          git rm -rf .
          cp -r public/* .
          
          # Add and commit
          git add -A
          git commit -m "Deploy Hugo site to GitHub Pages"
          
          # Push to gh-pages branch
          git push origin gh-pages --force